services:
  postgres:
    image: postgres:16
    container_name: pulse_news_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pulse_news
    ports:
      - "5432:5432"
    volumes:
      - pulse_news_pg:/var/lib/postgresql/data
volumes:
  pulse_news_pg:
